apiVersion: v1
kind: Service
metadata:
  name: hello-service
  annotations:
    configmanagement.gke.io/cluster-selector: selector-all-ships
spec:
  type: NodePort
  selector:
    greeting: hello
  ports:
  - name: world-port
    protocol: TCP
    port: 60000
    targetPort: 50000