apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  annotations:
    configmanagement.gke.io/cluster-selector: selector-ship2
spec:
  selector:
    matchLabels:
      greeting: hello
  replicas: 3
  template:
    metadata:
      labels:
        greeting: hello
    spec:
      containers:
      - name: hello-world
        image: "gcr.io/google-samples/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50000"